##  After learning so much in Numpy, It's time for an assignment. 

### You are a student and today is your Numpy test. The test will consist of 10 questions, purely related to code. You need to write code for the given questions.



#### Q-1 Import Numpy and Write the code to know the version of numpy you are working on ?
Your output should look like this. <br>
NOTE : Numpy version may be different for you.

Current Numpy version : 1.19.2


In [99]:
## write code here


#### Q - Create a numpy array having elements from 1 to 16 (inclusive) and print it.
Your output should look like this.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
## write code here


#### Q-3 You need to filter the previous array in such a way that , it only contains odd values.
Note : You have to use boolean indexing.<br>
Your output should look like this.

[ 1  3  5  7  9 11 13 15]


In [ ]:
## write code here


#### Q-4  Replace values that give remainder as 1 when divided by 2 from the above resulted array with 0
Your output should look like this.

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0]


In [ ]:
## write code here


#### Q-5  Change the shape of above resulted array to 4x4.
Your output should look like this.

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [ ]:
## write code here


#### Q-6 Stack the resulted array with itself vertically.
Your output should look like this.

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]
 [ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [23]:
## write code here


#### Q-7 On this vertical stacked resulted array, reverse the column order in alternate manner. column new order = [ 2,1,4,3 ]
Your output should look like this.

[[ 0  1  0  3]
 [ 0  5  0  7]
 [ 0  9  0 11]
 [ 0 13  0 15]
 [ 0  1  0  3]
 [ 0  5  0  7]
 [ 0  9  0 11]
 [ 0 13  0 15]]


In [33]:
## write code here


#### Q-8 Calculate , mean , median and mode of the resulting array.
Your output should look like this.

Mean : 4.0
Median : 0.5
Mode : 0


In [ ]:
## write code here


#### Q-9 Create an array of 5 values , that are selected at random from the above resulted array.
Your output should look like this.

Random Element Array : [15  0  5  3  0]


In [ ]:
## write code here


#### Q-10 Complete the function, that calculate the value of this function (a.k.a Binary Cross Entropy) using  Vectorization.
`Given -
    y  : a vector of N dimension,
    y^ : a vector of N dimension
    N : elements in y and y^
    Use : log base 2
    `

<img src="BCE.png" width=500>

Your output should be : 0.011179895048277702

In [94]:
def BCE(y, y_hat):
    ## write code here
    

In [95]:
y = np.array([0.13,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.1])
y_hat = np.array([0.2,0.3,0.4,0.3,0.6,0.8,0.7,0.5,0.8,0.1])

result = BCE(y, y_hat)
print(result)

0.011179895048277702
