# Numpy
    - Numpy is a numerical computing library for python.
    - Numpy support multi dimensional arrays and matrices
    - It has a lot of in-built mathematical functions
    
<img src="./imgs/numpy.png" width=400>

In [1]:
# installing numpy library
!pip install numpy

In [2]:
# importing numpy as np
import numpy as np

## Why Numpy ?
    - performs fast operations (because of Vectorization)
    - numpy arrays can be treated as vectors and matrices from linear algebra
    
<img src="./imgs/array.jpg" width=400>

In [3]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [4]:
%timeit [i**2 for i in lst]

2.77 µs ± 53.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
arr = np.array(lst)

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
%timeit arr**2

594 ns ± 11.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
# if i want to add 1 to each element of this vector
lst + [1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

In [11]:
# but it's possible in numpy array
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Numpy Basics

**array** : Fundamental element in numpy is homogenous array. Numpy Arrays can be 1D, 2D, 3D . . . nD
 
    - Different ways to create np array
        1. np.array()
        2. np.arange()

 

In [12]:
l = [1,5,8,9]

np_arr = np.array(l)

In [18]:
np_arr

array([1, 5, 8, 9])

In [14]:
type(np_arr)

numpy.ndarray

In [15]:
np_arr.ndim

1

In [16]:
#important
np_arr.shape

(4,)

**Another way of creating np array**

In [21]:
new_arr = np.arange(3, 11, 2)

In [22]:
new_arr

array([3, 5, 7, 9])

In [23]:
lst_2d = [ [1,2,3], [4,5,6], [7,8,9] ]

In [24]:
arr_2d = np.array(lst_2d)

In [25]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr_2d.ndim

2

In [27]:
arr_2d.shape

(3, 3)

## Special Arrays in Numpy
    - zeros()
    - ones()
    - diag()
    - identity()

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [34]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Indexing in Array

In [49]:
np.random.randint(10, 100 )

68

In [54]:
new_arr = np.random.randint(0, 20, (5,4))

In [55]:
new_arr

array([[ 1,  5, 19,  8],
       [11,  5, 12,  1],
       [ 6,  8,  2,  9],
       [15,  3,  9, 15],
       [ 2,  4, 14,  6]])

In [56]:
new_arr.shape

(5, 4)

In [57]:
# first row
new_arr[0]

array([ 1,  5, 19,  8])

In [58]:
# second last row
new_arr[-2]

array([15,  3,  9, 15])

In [59]:
# first element
print(new_arr[0, 0])

# last element
print(new_arr[4, 3])

1
6


**Array slicing**

In [60]:
new_arr

array([[ 1,  5, 19,  8],
       [11,  5, 12,  1],
       [ 6,  8,  2,  9],
       [15,  3,  9, 15],
       [ 2,  4, 14,  6]])

In [ ]:
arr[ start_row_idx : end_row_idx + 1, start_col_idx : end_col_idx+1]

In [64]:
new_arr[2: , 1: ]

array([[ 8,  2,  9],
       [ 3,  9, 15],
       [ 4, 14,  6]])

In [66]:
# third column only
new_arr[: , -1]

array([ 8,  1,  9, 15,  6])

In [68]:
new_arr[0,0] = 0

In [69]:
new_arr

array([[ 0,  5, 19,  8],
       [11,  5, 12,  1],
       [ 6,  8,  2,  9],
       [15,  3,  9, 15],
       [ 2,  4, 14,  6]])

In [72]:
# masking 
mask = new_arr > 10
print(mask)

[[False False  True False]
 [ True False  True False]
 [False False False False]
 [ True False False  True]
 [False False  True False]]


In [73]:
np.sum(mask)

6

In [75]:
# get all values greater than 10
new_arr[mask]

array([19, 11, 12, 15, 15, 14])

In [76]:
new_arr

array([[ 0,  5, 19,  8],
       [11,  5, 12,  1],
       [ 6,  8,  2,  9],
       [15,  3,  9, 15],
       [ 2,  4, 14,  6]])

In [78]:
new_arr[2: , 2:] = 0

In [79]:
new_arr

array([[ 0,  5, 19,  8],
       [11,  5, 12,  1],
       [ 6,  8,  0,  0],
       [15,  3,  0,  0],
       [ 2,  4,  0,  0]])

## Basic Operations in Arrays

In [80]:
a = np.array([10,20,30,40])
b = np.arange(1, 5)

In [81]:
a

array([10, 20, 30, 40])

In [82]:
b

array([1, 2, 3, 4])

In [83]:
a + b

array([11, 22, 33, 44])

In [84]:
a - b

array([ 9, 18, 27, 36])

In [85]:
a * b

array([ 10,  40,  90, 160])

In [ ]:
b**2

In [86]:
# masking
a>15

array([False,  True,  True,  True])

In [87]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [88]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

**Matrix Product**

In [89]:
A = np.random.randint(0, 5, (3, 4))
B = np.random.randint(0, 5, (4, 2))

In [90]:
A

array([[3, 3, 3, 3],
       [0, 4, 3, 3],
       [0, 3, 0, 1]])

In [91]:
B

array([[4, 2],
       [0, 2],
       [4, 4],
       [3, 4]])

In [92]:
# Dot product
np.dot(A, B)

array([[33, 36],
       [21, 32],
       [ 3, 10]])

## More Operations on Arrays

In [93]:
A = np.arange(0, 24)

In [96]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [97]:
A = A.reshape(6,4)

In [100]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [101]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [102]:
np.sum(A)

276

In [103]:
np.max(A)

23

In [104]:
np.mean(A)

11.5

In [105]:
np.std(A)

6.922186552431729

In [106]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [108]:
np.sum(A, axis=0)

array([60, 66, 72, 78])

In [109]:
np.mean(A, axis = 1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

## Shape Manipulation

In [111]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [112]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [113]:
A.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [114]:
A.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [115]:
np.transpose(A)

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

**Stacking of arrays**
    - vstack
    - hstack

In [118]:
a = np.random.randint(0, 10, (2,2))
b = np.random.randint(0, 10, (2,2))

In [119]:
a

array([[6, 0],
       [8, 6]])

In [120]:
b

array([[9, 6],
       [5, 4]])

In [123]:
np.hstack((a,b))

array([[6, 0, 9, 6],
       [8, 6, 5, 4]])

In [126]:
np.vstack((a,b))

array([[6, 0],
       [8, 6],
       [9, 6],
       [5, 4]])

## Broadcasting
    - First Rule of Numpy : 2 Arrays can performs opertions only when they have same shapes
    - broadcasting let two arrays of different shapes to do some operations.
        - A small array will repeat itself, and convert to the same shape as of another array.

In [127]:
A = np.random.randint(0, 10, size=(3,3))
a = np.array([[1,2,3]])

In [128]:
A

array([[8, 0, 0],
       [3, 7, 1],
       [7, 0, 8]])

In [131]:
a

array([[1, 2, 3]])

In [133]:
print(A.shape, a.shape)

(3, 3) (1, 3)


In [134]:
A + a

array([[ 9,  2,  3],
       [ 4,  9,  4],
       [ 8,  2, 11]])

In [137]:
a.T

array([[1],
       [2],
       [3]])

In [138]:
A + a.T

array([[ 9,  1,  1],
       [ 5,  9,  3],
       [10,  3, 11]])

In [139]:
A

array([[8, 0, 0],
       [3, 7, 1],
       [7, 0, 8]])

In [140]:
A + 4

array([[12,  4,  4],
       [ 7, 11,  5],
       [11,  4, 12]])

## Vectorization
    - performing operations directly on Arrays

In [161]:
p1 = np.array([1,2, 4, 7, -2, 9, 6, 0])
p2 = np.array([5,5, 8, 2, -9, 2, 1, 6])

In [163]:
s = 0
for i in range(8):
    s += (p2[i] - p1[i])**2
    
print(s**0.5)

15.0


In [165]:
# efficient
def distance(p1, p2):
    return np.sqrt(np.sum((p2-p1)**2))

In [168]:
distance(p1, p2)

15.0

## Challenges:
 
1/2m ∑ ( a - b )<sup>2</sup>